server:
    port: 8085

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j:
    circuitbreaker:
        instances:
            zipCodeInfo:
                failureRateThreshold: 50
                minimumNumberOfCalls: 20
                slidingWindowType: TIME_BASED
                slidingWindowSize: 10
                waitDurationInOpenState: 50s
                permittedNumberOfCallsInHalfOpenState: 3

client:
    api:
        url-base: https://viacep.com.br
